Repository TaskWeaver/backend, pull requests merged in 2024-03, with the labels that each got.

#50 프로젝트 전체 조회 repsonse 수정
  src/main/java/backend/taskweaver/domain/project/controller/ProjectController.java
  src/main/java/backend/taskweaver/domain/project/dto/GetAllProjectResponse.java
  src/main/java/backend/taskweaver/domain/project/service/ProjectService.java
  src/main/java/backend/taskweaver/domain/project/service/ProjectServiceImpl.java
  src/main/java/backend/taskweaver/global/converter/ProjectConverter.java
Labels: amy🌱

#58 feat/#57
  build.gradle
  src/main/java/backend/taskweaver/domain/task/controller/TaskController.java
  src/main/java/backend/taskweaver/domain/task/dto/TaskRequest.java
  src/main/java/backend/taskweaver/domain/task/dto/TaskResponse.java
  src/main/java/backend/taskweaver/domain/task/entity/Task.java
  src/main/java/backend/taskweaver/domain/task/repository/TaskMemberRepository.java
  src/main/java/backend/taskweaver/domain/task/service/TaskService.java
  src/main/java/backend/taskweaver/domain/task/service/TaskServiceImpl.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
  src/main/java/backend/taskweaver/global/converter/TaskConverter.java
Labels: conan🕵️

#55 팀장 권한 변경 기능
  src/main/java/backend/taskweaver/domain/team/controller/TeamController.java
  src/main/java/backend/taskweaver/domain/team/dto/TeamLeaderRequest.java
  src/main/java/backend/taskweaver/domain/team/dto/TeamLeaderResponse.java
  src/main/java/backend/taskweaver/domain/team/entity/TeamMember.java
  src/main/java/backend/taskweaver/domain/team/repository/TeamMemberRepository.java
  src/main/java/backend/taskweaver/domain/team/repository/TeamRepository.java
  src/main/java/backend/taskweaver/domain/team/service/TeamService.java
  src/main/java/backend/taskweaver/domain/team/service/TeamServiceImpl.java
  src/main/java/backend/taskweaver/global/converter/TeamConverter.java
Labels: bboggo :penguin:
