Repository TaskWeaver/backend, pull requests merged in 2024-07, with the labels that each got.

#93 프로젝트 DTO 파일 형식 record에서 일반 클래스로 변경
  src/main/java/backend/taskweaver/domain/project/controller/ProjectController.java
  src/main/java/backend/taskweaver/domain/project/dto/ProjectMemberResponse.java
  src/main/java/backend/taskweaver/domain/project/dto/ProjectRequest.java
  src/main/java/backend/taskweaver/domain/project/dto/ProjectResponse.java
  src/main/java/backend/taskweaver/domain/project/dto/UpdateStateRequest.java
  src/main/java/backend/taskweaver/domain/project/entity/Project.java
  src/main/java/backend/taskweaver/domain/project/service/ProjectServiceImpl.java
  src/main/java/backend/taskweaver/global/converter/ProjectConverter.java
  src/test/java/backend/taskweaver/domain/project/service/ProjectServiceImplTest.java
  src/test/java/backend/taskweaver/domain/project/service/ProjectServiceImplUnitTest.java
Labels: amy🌱

#95 Feat/#91 회원가입시 이미지 업로드 기능 구현
  src/main/java/backend/taskweaver/domain/files/service/S3Service.java
  src/main/java/backend/taskweaver/domain/member/controller/SignController.java
  src/main/java/backend/taskweaver/domain/member/dto/SignUpRequest.java
  src/main/java/backend/taskweaver/domain/member/dto/SignUpResponse.java
  src/main/java/backend/taskweaver/domain/member/service/SignService.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
  src/main/java/backend/taskweaver/global/config/SwaggerConfig.java
  src/main/java/backend/taskweaver/global/converter/MemberConverter.java
Labels: bboggo :penguin:

#99 Feat/#90 회원 탈퇴 api, 회원 코드에 Validation 추가
  build.gradle
  src/main/generated/backend/taskweaver/domain/member/entity/QMember.java
  src/main/java/backend/taskweaver/domain/member/controller/MemberController.java
  src/main/java/backend/taskweaver/domain/member/controller/SignController.java
  src/main/java/backend/taskweaver/domain/member/dto/SignUpRequest.java
  src/main/java/backend/taskweaver/domain/member/entity/Member.java
  src/main/java/backend/taskweaver/domain/member/service/MemberService.java
  src/main/java/backend/taskweaver/domain/project/repository/ProjectMemberRepository.java
  src/main/java/backend/taskweaver/domain/project/repository/ProjectRepository.java
  src/main/java/backend/taskweaver/domain/task/repository/TaskMemberRepository.java
  src/main/java/backend/taskweaver/domain/team/repository/TeamMemberRepository.java
  src/main/java/backend/taskweaver/domain/team/repository/TeamRepository.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
Labels: amy🌱

#100 Feat/#98 팀 조회 수정 및 스웨거 설정
  src/main/java/backend/taskweaver/domain/member/controller/SignController.java
  src/main/java/backend/taskweaver/domain/team/dto/TeamResponse.java
  src/main/java/backend/taskweaver/global/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/backend/taskweaver/global/converter/TeamConverter.java
Labels: bboggo :penguin:

#104 Feat/#103 회원가입시 비밀번호 정규식 수정
  src/main/java/backend/taskweaver/domain/member/dto/SignUpRequest.java
Labels: amy🌱

#102 Feat/#101 팀 삭제 기능
  src/main/java/backend/taskweaver/domain/team/controller/TeamController.java
  src/main/java/backend/taskweaver/domain/team/dto/TeamResponse.java
  src/main/java/backend/taskweaver/domain/team/entity/Team.java
  src/main/java/backend/taskweaver/domain/team/service/TeamService.java
  src/main/java/backend/taskweaver/domain/team/service/TeamServiceImpl.java
  src/main/java/backend/taskweaver/global/converter/TeamConverter.java
Labels: bboggo :penguin:

#110 Feat/#109
  README.md
  build.gradle
  src/main/java/backend/taskweaver/domain/member/controller/MemberController.java
  src/main/java/backend/taskweaver/domain/member/controller/SignController.java
  src/main/java/backend/taskweaver/domain/member/dto/EmailMessage.java
  src/main/java/backend/taskweaver/domain/member/dto/EmailRequest.java
  src/main/java/backend/taskweaver/domain/member/dto/EmailResponse.java
  src/main/java/backend/taskweaver/domain/member/dto/OauthSignUpResponse.java
  src/main/java/backend/taskweaver/domain/member/entity/oauth/KakaoProfile.java
  src/main/java/backend/taskweaver/domain/member/entity/oauth/NaverProfile.java
  src/main/java/backend/taskweaver/domain/member/entity/oauth/OauthToken.java
  src/main/java/backend/taskweaver/domain/member/service/EmailService.java
  src/main/java/backend/taskweaver/domain/member/service/SignService.java
  src/main/java/backend/taskweaver/domain/project/entity/ProjectState.java
  src/main/java/backend/taskweaver/domain/project/repository/ProjectStateRepository.java
  src/main/java/backend/taskweaver/domain/task/controller/TaskController.java
  src/main/java/backend/taskweaver/domain/task/dto/TaskRequest.java
  src/main/java/backend/taskweaver/domain/task/dto/TaskResponse.java
  src/main/java/backend/taskweaver/domain/task/entity/Task.java
  src/main/java/backend/taskweaver/domain/task/repository/TaskRepository.java
  src/main/java/backend/taskweaver/domain/task/service/TaskService.java
  src/main/java/backend/taskweaver/domain/task/service/TaskServiceImpl.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
  src/main/java/backend/taskweaver/global/config/SecurityConfig.java
  src/main/java/backend/taskweaver/global/converter/TaskConverter.java
  src/main/java/backend/taskweaver/global/security/TokenProvider.java
  src/main/resources/application
  src/main/resources/templates/logo.svg
  src/main/resources/templates/sendEmail.html
Labels: conan🕵️

#105 Feat/#67 팀장 권한 변경 api 수정
  src/main/java/backend/taskweaver/domain/team/controller/TeamController.java
  src/main/java/backend/taskweaver/domain/team/service/TeamServiceImpl.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
Labels: bboggo :penguin:

#113 fix: 이메일 인증에 중복 체크 추가
  src/main/java/backend/taskweaver/domain/member/service/EmailService.java
  src/main/java/backend/taskweaver/domain/member/service/MemberService.java
Labels: conan🕵️
