Repository TaskWeaver/backend, pull requests merged in 2024-02, with the labels that each got.

#19 Feat/#8
  src/main/java/backend/taskweaver/domain/project/controller/ProjectController.java
  src/main/java/backend/taskweaver/domain/project/dto/ProjectRequest.java
  src/main/java/backend/taskweaver/domain/project/dto/ProjectResponse.java
  src/main/java/backend/taskweaver/domain/project/entity/Project.java
  src/main/java/backend/taskweaver/domain/project/entity/ProjectMember.java
  src/main/java/backend/taskweaver/domain/project/entity/ProjectState.java
  src/main/java/backend/taskweaver/domain/project/entity/ProjectStateMapping.java
  src/main/java/backend/taskweaver/domain/project/entity/enums/ProjectStateName.java
  src/main/java/backend/taskweaver/domain/project/repository/ProjectMemberRepository.java
  src/main/java/backend/taskweaver/domain/project/repository/ProjectRepository.java
  src/main/java/backend/taskweaver/domain/project/repository/ProjectStateRepository.java
  src/main/java/backend/taskweaver/domain/project/service/ProjectService.java
  src/main/java/backend/taskweaver/domain/project/service/ProjectServiceImpl.java
  src/main/java/backend/taskweaver/domain/team/repository/TeamMemberRepository.java
  src/main/java/backend/taskweaver/global/code/ApiResponse.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
  src/main/java/backend/taskweaver/global/converter/ProjectConverter.java
  src/main/java/backend/taskweaver/global/exception/handler/GlobalExceptionHandler.java
Labels: amy🌱

#29 feat: task create
  src/main/java/backend/taskweaver/domain/task/controller/TaskController.java
  src/main/java/backend/taskweaver/domain/task/dto/TaskRequest.java
  src/main/java/backend/taskweaver/domain/task/dto/TaskResponse.java
  src/main/java/backend/taskweaver/domain/task/entity/Task.java
  src/main/java/backend/taskweaver/domain/task/entity/TaskMember.java
  src/main/java/backend/taskweaver/domain/task/entity/enums/TaskStateName.java
  src/main/java/backend/taskweaver/domain/task/repository/TaskMemberRepository.java
  src/main/java/backend/taskweaver/domain/task/repository/TaskRepository.java
  src/main/java/backend/taskweaver/domain/task/service/TaskService.java
  src/main/java/backend/taskweaver/domain/task/service/TaskServiceImpl.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
  src/main/java/backend/taskweaver/global/converter/TaskConverter.java
Labels: conan🕵️

#30 fix: task create mapping change
  src/main/java/backend/taskweaver/domain/task/controller/TaskController.java
Labels: conan🕵️

#32 fix: change task create request and response
  src/main/java/backend/taskweaver/domain/task/controller/TaskController.java
  src/main/java/backend/taskweaver/domain/task/dto/TaskRequest.java
  src/main/java/backend/taskweaver/domain/task/dto/TaskResponse.java
  src/main/java/backend/taskweaver/domain/task/service/TaskService.java
  src/main/java/backend/taskweaver/domain/task/service/TaskServiceImpl.java
  src/main/java/backend/taskweaver/global/converter/TaskConverter.java
Labels: conan🕵️

#34 Feat/#16 팀 조회 기능
  src/main/java/backend/taskweaver/domain/team/controller/TeamController.java
  src/main/java/backend/taskweaver/domain/team/dto/TeamInviteResponse.java
  src/main/java/backend/taskweaver/domain/team/dto/TeamResponse.java
  src/main/java/backend/taskweaver/domain/team/entity/Team.java
  src/main/java/backend/taskweaver/domain/team/repository/TeamMemberRepository.java
  src/main/java/backend/taskweaver/domain/team/service/TeamService.java
  src/main/java/backend/taskweaver/domain/team/service/TeamServiceImpl.java
  src/main/java/backend/taskweaver/global/converter/TeamConverter.java
Labels: bboggo :penguin:

#43 Feat/#42 비밀번호 변경 api
  src/main/java/backend/taskweaver/domain/member/controller/MemberController.java
  src/main/java/backend/taskweaver/domain/member/dto/UpdatePasswordRequest.java
  src/main/java/backend/taskweaver/domain/member/entity/Member.java
  src/main/java/backend/taskweaver/domain/member/service/MemberService.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
Labels: amy🌱

#40 Feat/#20 프로젝트 삭제 api
  src/main/java/backend/taskweaver/domain/project/controller/ProjectController.java
  src/main/java/backend/taskweaver/domain/project/entity/Project.java
  src/main/java/backend/taskweaver/domain/project/entity/ProjectMember.java
  src/main/java/backend/taskweaver/domain/project/repository/ProjectMemberRepository.java
  src/main/java/backend/taskweaver/domain/project/service/ProjectService.java
  src/main/java/backend/taskweaver/domain/project/service/ProjectServiceImpl.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
Labels: amy🌱

#41 Feat/#9 프로젝트 수정 api, 프로젝트 상태 변경 api
  src/main/java/backend/taskweaver/domain/project/controller/ProjectController.java
  src/main/java/backend/taskweaver/domain/project/dto/ProjectRequest.java
  src/main/java/backend/taskweaver/domain/project/dto/UpdateStateRequest.java
  src/main/java/backend/taskweaver/domain/project/entity/Project.java
  src/main/java/backend/taskweaver/domain/project/entity/ProjectMember.java
  src/main/java/backend/taskweaver/domain/project/entity/ProjectState.java
  src/main/java/backend/taskweaver/domain/project/repository/ProjectMemberRepository.java
  src/main/java/backend/taskweaver/domain/project/service/ProjectService.java
  src/main/java/backend/taskweaver/domain/project/service/ProjectServiceImpl.java
  src/main/java/backend/taskweaver/global/code/ErrorCode.java
  src/main/java/backend/taskweaver/global/code/SuccessCode.java
Labels: amy🌱
